"""Built-in /peat research and /peat digest workflows.

These are *prompt builders*, not executors. The CLI receives the prompt
and dispatches it to the live agent (which has the right tools wired in)
exactly the same way ``/replay run`` and ``/qa new`` do. Keeping these
as pure prompt-builders keeps them deterministic and easy to test.
"""

from __future__ import annotations

import json
import logging
import time
from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from bog_agents_cli.peat.persona import PeatPersona

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# /peat research
# ---------------------------------------------------------------------------


def build_research_prompt(
    persona: PeatPersona,
    *,
    topic: str,
    focus: str = "",
    config_dir: Path,
) -> str:
    """Render a multi-step research prompt for ``topic``.

    The prompt directs the agent through a deliberate plan: scoping →
    search → fetch sources → cross-check → produce a structured report.
    The agent uses whatever search/web/MCP tools it has available; if
    none, it stops and tells the user what to enable.

    Args:
        persona: Resolved persona.
        topic: The thing to research (a product, library, vendor, etc.).
        focus: Optional comma-separated angles to weight (``"security,
            pricing, integrations"``).
        config_dir: User config root — used to compute the report path.

    Returns:
        Prompt for the agent.
    """
    output_dir = config_dir / "peat" / "research"
    output_dir.mkdir(parents=True, exist_ok=True)
    safe_slug = "".join(c for c in topic.lower() if c.isalnum() or c in "-_")[:60] or "topic"
    stamp = time.strftime("%Y%m%d", time.gmtime())
    output_path = output_dir / f"{stamp}-{safe_slug}.md"

    focus_block = ""
    if focus:
        focus_items = [f.strip() for f in focus.split(",") if f.strip()]
        if focus_items:
            focus_block = "\n## Focus angles\n\n" + "\n".join(f"- {f}" for f in focus_items) + "\n"

    return (
        f"{persona.to_system_prompt()}\n"
        "\n## Deep research request\n\n"
        f"Research this topic and produce a structured report:\n\n**{topic}**\n"
        f"{focus_block}\n"
        "Save the final report to:\n\n"
        f"  `{output_path}`\n\n"
        "## Method — follow these phases in order\n\n"
        "**Phase 1: Scope.** Write 3 sub-questions you'll answer to fully address "
        "the topic. State them up front in your scratch work. If the topic is "
        "ambiguous, ask the user *one* clarifying question and stop until they "
        "answer.\n\n"
        "**Phase 2: Search.** Use the web-search tool (or whatever search-capable "
        "MCP tool is configured) to find at least 5 distinct sources. Prefer "
        "primary sources (official docs, vendor pages, RFCs, peer-reviewed "
        "papers) over blog posts. If no search tool is available, stop and tell "
        "the user which one to enable.\n\n"
        "**Phase 3: Fetch & extract.** For each source, fetch the actual page "
        "content (don't rely on snippets), and extract the relevant sections. "
        "Note publication date, author/org, and confidence level (primary vs "
        "secondary).\n\n"
        "**Phase 4: Cross-check.** Identify points where sources disagree. Call "
        "those out explicitly in the report — do not silently pick a winner.\n\n"
        "**Phase 5: Write the report.** Use this exact structure:\n\n"
        "    # <topic>\n\n"
        "    *Generated by Peat on <date>.*\n\n"
        "    ## TL;DR\n\n"
        "    <3-5 bullet points the user can scan in 30 seconds.>\n\n"
        "    ## Key findings\n\n"
        "    <one section per sub-question. Include specifics, not platitudes.>\n\n"
        "    ## Where sources disagree\n\n"
        "    <bulleted list of disagreements with one-line context each.>\n\n"
        "    ## Open questions\n\n"
        "    <things you couldn't resolve, with what would resolve them.>\n\n"
        "    ## Sources\n\n"
        "    <numbered list. for each: title, URL, date, primary/secondary, "
        "    1-line takeaway.>\n\n"
        f"    {persona.sign_off}\n\n"
        "## Honesty rules\n\n"
        "- If a source contradicts something you 'know' from training, prefer "
        "the source. Note the discrepancy in 'Where sources disagree'.\n"
        "- If you couldn't find good evidence for a claim, say so — never invent.\n"
        "- If a search returned zero useful results, say so plainly. Don't pad.\n"
    )


# ---------------------------------------------------------------------------
# /peat digest
# ---------------------------------------------------------------------------


def collect_digest_inputs(
    config_dir: Path,
    *,
    project_root: Path | None = None,
    days: int = 7,
) -> dict[str, Any]:
    """Gather pointers to recent /qa results, /replay recordings, and inbox notes.

    This does NOT read full file contents — it produces a manifest of paths
    and one-line summaries. The agent reads what it actually needs in the
    digest prompt, keeping the prompt small.

    Args:
        config_dir: User config root.
        project_root: Project root (for project-scoped /qa plans). If None,
            project plans are skipped.
        days: Look-back window in days.

    Returns:
        Dict with keys: ``qa_plans``, ``qa_results``, ``replays``,
        ``inbox``, ``research``, ``window_start_iso``.
    """
    cutoff = time.time() - days * 86400
    out: dict[str, Any] = {
        "qa_plans": [],
        "qa_results": [],
        "replays": [],
        "inbox": [],
        "research": [],
        "window_start_iso": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime(cutoff)),
        "days": days,
    }

    # Replays.
    replays_dir = config_dir / "replays"
    if replays_dir.exists():
        for p in replays_dir.iterdir():
            if p.suffix.lower() in (".yaml", ".yml", ".json") and p.stat().st_mtime >= cutoff:
                out["replays"].append({"path": str(p), "mtime": p.stat().st_mtime})

    # Research artifacts already produced.
    research_dir = config_dir / "peat" / "research"
    if research_dir.exists():
        for p in research_dir.iterdir():
            if p.suffix.lower() == ".md" and p.stat().st_mtime >= cutoff:
                out["research"].append({"path": str(p), "mtime": p.stat().st_mtime})

    # Inbox — peat's own queued notifications.
    inbox = config_dir / "peat" / "inbox.json"
    if inbox.is_file():
        try:
            entries = json.loads(inbox.read_text(encoding="utf-8"))
            if isinstance(entries, list):
                # Take only entries within the window.
                out["inbox"] = entries[-200:]
        except (OSError, json.JSONDecodeError):
            pass

    # QA — both plans and results — only when we know the project root.
    if project_root is not None:
        plans_dir = project_root / ".bog-agents" / "qa-plans"
        if plans_dir.exists():
            for p in plans_dir.iterdir():
                if p.suffix.lower() in (".yaml", ".yml") and p.stat().st_mtime >= cutoff:
                    out["qa_plans"].append({"path": str(p), "mtime": p.stat().st_mtime})
        results_root = project_root / ".bog-agents" / "qa-results"
        if results_root.exists():
            for plan_dir in results_root.iterdir():
                if not plan_dir.is_dir():
                    continue
                for run_file in plan_dir.iterdir():
                    if run_file.suffix.lower() in (".md", ".json") and run_file.stat().st_mtime >= cutoff:
                        out["qa_results"].append(
                            {
                                "plan_id": plan_dir.name,
                                "path": str(run_file),
                                "mtime": run_file.stat().st_mtime,
                            }
                        )

    # Sort each list newest first.
    for key in ("replays", "research", "qa_plans", "qa_results"):
        out[key].sort(key=lambda x: x["mtime"], reverse=True)
    return out


def build_digest_prompt(
    persona: PeatPersona,
    *,
    inputs: dict[str, Any],
    config_dir: Path,
) -> str:
    """Render a digest-builder prompt from a manifest produced by ``collect_digest_inputs``.

    Args:
        persona: Resolved persona.
        inputs: Output of :func:`collect_digest_inputs`.
        config_dir: User config root — output is saved under
            ``peat/digests/``.

    Returns:
        Prompt for the agent.
    """
    digests_dir = config_dir / "peat" / "digests"
    digests_dir.mkdir(parents=True, exist_ok=True)
    stamp = time.strftime("%Y%m%d", time.gmtime())
    output_path = digests_dir / f"{stamp}-digest.md"

    manifest_lines: list[str] = []

    def _summarize(key: str, label: str) -> None:
        items = inputs.get(key, [])
        if not items:
            manifest_lines.append(f"- {label}: (none in window)")
            return
        manifest_lines.append(f"- {label}: {len(items)} item(s)")
        for item in items[:8]:
            path = item.get("path", "?")
            manifest_lines.append(f"    - {path}")

    _summarize("qa_results", "QA run artifacts")
    _summarize("qa_plans", "QA plans")
    _summarize("replays", "Replay recordings")
    _summarize("research", "Research reports")

    inbox_count = len(inputs.get("inbox", []))
    manifest_lines.append(f"- Peat inbox notifications: {inbox_count} entr(y|ies)")

    return (
        f"{persona.to_system_prompt()}\n"
        "\n## Digest builder\n\n"
        f"Build a personalized digest covering the last {inputs.get('days', 7)} days. "
        "Read the listed files (use `read_file` and `read_many_files`), pull out "
        "what's actually interesting, and write a single readable digest the user "
        "can skim in two minutes.\n\n"
        "Save the digest to:\n\n"
        f"  `{output_path}`\n\n"
        "## Manifest of recent activity\n\n"
        + "\n".join(manifest_lines)
        + "\n\n## Digest structure\n\n"
        "    # Personal digest — <date>\n\n"
        "    ## What changed\n"
        "    <bullet list — recent QA failures/passes, replays you re-ran, "
        "    research reports.>\n\n"
        "    ## Highlights worth your time\n"
        "    <2-4 items the user should look at, with one-line 'why'.>\n\n"
        "    ## Things I noticed\n"
        "    <patterns across the artifacts. e.g. 'AC2 has failed 3 weeks in a "
        "    row in plan qa-checkout — likely flaky, worth investigating'.>\n\n"
        "    ## Open from your inbox\n"
        "    <surface unhandled inbox notifications by job.>\n\n"
        f"    {persona.sign_off}\n\n"
        "## Honesty rules\n\n"
        "- Don't pad. If nothing meaningful happened in a section, say 'nothing "
        "noteworthy this period'.\n"
        "- Don't reproduce QA report tables — link to them.\n"
        "- Never include any value from a SecretStr or vault key.\n"
    )
