"""Bootstrap an SSH sandbox task by writing files and spawning the worker."""

from __future__ import annotations

import base64
import json
import subprocess  # noqa: S404 - required to spawn the detached worker
import sys
import time
from pathlib import Path

payload = json.loads(base64.b64decode(sys.argv[1]).decode("utf-8"))
worker_source = base64.b64decode(sys.argv[2]).decode("utf-8")

task_dir = Path(str(payload["task_dir"])).expanduser()
task_dir.mkdir(parents=True, exist_ok=True)
payload_path = task_dir / "payload.json"
worker_path = task_dir / "worker.py"
prompt_path = Path(str(payload["prompt_file"])).expanduser()
status_path = Path(str(payload["status_file"])).expanduser()

payload_path.write_text(json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8")
worker_path.write_text(worker_source, encoding="utf-8")
prompt_path.write_text(str(payload["prompt"]), encoding="utf-8")
status_path.write_text(
    json.dumps(
        {
            "task_id": payload["task_id"],
            "label": payload["label"],
            "prompt": payload["prompt"],
            "status": "pending",
            "provider": "ssh",
            "ssh_target": payload["ssh_target"],
            "workspace_dir": payload["workspace_dir"],
            "branch": payload["sandbox_branch"],
            "repo_name": payload["repo_name"],
            "task_dir": payload["task_dir"],
            "submitted_at": time.time(),
        },
        indent=2,
        sort_keys=True,
    ),
    encoding="utf-8",
)

process = subprocess.Popen(  # noqa: S603 - worker path is generated by this script
    [sys.executable, str(worker_path), str(payload_path)],
    cwd=str(task_dir),
    stdout=subprocess.DEVNULL,
    stderr=subprocess.DEVNULL,
    start_new_session=True,
)

status_path.write_text(
    json.dumps(
        {
            "task_id": payload["task_id"],
            "label": payload["label"],
            "prompt": payload["prompt"],
            "status": "running",
            "provider": "ssh",
            "ssh_target": payload["ssh_target"],
            "workspace_dir": payload["workspace_dir"],
            "branch": payload["sandbox_branch"],
            "repo_name": payload["repo_name"],
            "task_dir": payload["task_dir"],
            "submitted_at": time.time(),
            "pid": process.pid,
        },
        indent=2,
        sort_keys=True,
    ),
    encoding="utf-8",
)
sys.stdout.write(
    json.dumps(
        {
            "task_id": payload["task_id"],
            "pid": process.pid,
            "status_file": str(status_path),
            "workspace_dir": payload["workspace_dir"],
            "task_dir": payload["task_dir"],
            "branch": payload["sandbox_branch"],
            "repo_name": payload["repo_name"],
        }
    )
)
