# Homebrew formula for bog-agents-cli (ROADMAP #61).
#
# Lives in the tap `bogware/homebrew-tap` (Formula/bog-agents-cli.rb); this copy is the
# source of truth. Refresh for a release:
#
#   1. update `url` / `sha256` to the sdist on PyPI for the new version
#      (https://pypi.org/project/bog-agents-cli/#files → Source Distribution),
#   2. regenerate the resource stanzas from the lock:
#        brew update-python-resources --print-only packaging/homebrew/bog-agents-cli.rb
#      (paste the output between the RESOURCES markers; provider extras are not
#      pinned here — users add them with `pipx inject`-style `brew` isn't ideal for
#      extras, so the formula installs the `anthropic` and `openai` extras),
#   3. `brew install --build-from-source ./bog-agents-cli.rb && brew test bog-agents-cli`.
class BogAgentsCli < Formula
  include Language::Python::Virtualenv

  desc "Coding agent that lives in your terminal, built on LangGraph"
  homepage "https://github.com/bogware/bog-agents"
  url "https://files.pythonhosted.org/packages/source/b/bog-agents-cli/bog_agents_cli-0.9.13.tar.gz"
  sha256 "REPLACE_WITH_SDIST_SHA256"
  license "MIT"
  head "https://github.com/bogware/bog-agents.git", branch: "main"

  depends_on "python@3.12"
  depends_on "rust" => :build # pydantic-core / tiktoken wheels fall back to source on new Python minors

  # --- RESOURCES (generated by `brew update-python-resources`) -----------------
  # resource "bog-agents" do
  #   url "https://files.pythonhosted.org/packages/source/b/bog-agents/bog_agents-0.9.13.tar.gz"
  #   sha256 "..."
  # end
  # --- END RESOURCES -------------------------------------------------------------

  def install
    # Provider extras: Claude + OpenAI are the ones the README leads with.
    venv = virtualenv_create(libexec, "python3.12")
    venv.pip_install resources
    venv.pip_install_and_link buildpath, build_isolation: true
    venv.pip_install "bog-agents-cli[anthropic,openai]==#{version}"
  end

  def caveats
    <<~EOS
      Set a provider key and run `bog-agents`:
        export ANTHROPIC_API_KEY=sk-ant-...
        bog-agents --doctor
      Other providers: `#{libexec}/bin/pip install 'bog-agents-cli[all-providers]'`.
    EOS
  end

  test do
    assert_match "bog-agents-cli", shell_output("#{bin}/bog-agents --version")
    assert_match "Health Check", shell_output("#{bin}/bog-agents --doctor")
  end
end
