"""Theme registry: built-in Textual themes plus user-defined themes.

Textual resolves colors from the *active theme* (`App.theme`). Historically
the CLI shipped no registered theme and instead hard-coded the matte-swamp
palette as `$primary: …` overrides at the top of `app.tcss`. Those CSS-level
overrides shadowed whatever theme was active, which is why a `/theme` command
could never actually change anything.

This module makes the palette a real, registered Textual `Theme` named
`bog` and sets it as the default, so the `app.tcss` override block can be
removed while leaving the default look **byte-identical**. Every variable the
app's CSS references (`$primary`, `$surface`, `$highlight`, `$boundary`,
`$text`, `$accent`, …) resolves to the exact same hex it did before — the
lighten/darken/highlight/boundary/text variants that Textual would otherwise
*derive* are pinned in the theme's `variables` dict so no rounding or hue
drift can creep in. See `tests/unit_tests/test_theme.py`.

Extra built-in themes (`bog-light`, `abyss`, `ember`) and user themes give
`/theme` something to switch between. Users add themes under `[themes.<name>]`
in `~/.bog-agents/config.toml`; see `load_user_theme_specs()`.

Three CSS variables — `highlight`, `highlight-soft`, and `boundary` — are
app-specific and are *not* generated by Textual's color system, so every
registered theme must supply them (via `variables`) or the referencing CSS
rules would fail to resolve. Built-in specs always carry them; user themes
fall back to the base palette's values when omitted.
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from collections.abc import Iterable, Mapping

    from textual.app import App
    from textual.theme import Theme

logger = logging.getLogger(__name__)

DEFAULT_THEME_NAME = "bog"
"""Theme applied on startup when the user has saved no preference."""

_HEX_RE = re.compile(r"^#(?:[0-9A-Fa-f]{6}|[0-9A-Fa-f]{8})$")
"""Matches a 7- or 9-char hex color (`#RRGGBB` / `#RRGGBBAA`).

Textual's `Color.parse` would also validate, but a local regex keeps the
registry importable on the `bog-agents --help` cold path without importing
Textual (~0.5s).
"""

# App-specific CSS variables Textual does NOT generate. Every theme must
# provide these three or CSS that references `$highlight` / `$highlight-soft`
# / `$boundary` (e.g. the input divider, hover veils) fails to resolve.
_REQUIRED_CUSTOM_VARS = ("highlight", "highlight-soft", "boundary")

# CSS variables a user theme may pin directly (beyond the base Theme fields).
# Anything not listed here is either a base field or left for Textual to
# derive from the base fields.
_PINNABLE_VARS = (
    "primary-lighten-1",
    "primary-lighten-2",
    "primary-darken-1",
    "primary-darken-2",
    "surface-lighten-1",
    "surface-darken-1",
    "highlight",
    "highlight-soft",
    "boundary",
    "text",
    "text-muted",
    "warning",
)


@dataclass(frozen=True, slots=True)
class ThemeSpec:
    """A theme as a set of base colors plus pinned CSS-variable overrides.

    The base fields map straight onto Textual's `Theme` fields. `variables`
    pins the derived / app-specific variables that must not be left to
    Textual's derivation (either to stay byte-identical with the old palette,
    or because Textual does not generate them at all — see
    `_REQUIRED_CUSTOM_VARS`).
    """

    name: str
    """Registry key and `App.theme` value (e.g. `'bog'`)."""

    label: str
    """Human-readable name shown in the picker (e.g. `'Bog (peat)'`)."""

    dark: bool
    """Whether this is a dark theme variant."""

    primary: str
    secondary: str
    background: str
    surface: str
    foreground: str
    success: str
    warning: str
    error: str
    accent: str

    variables: Mapping[str, str] = field(default_factory=dict)
    """Pinned CSS variables merged over Textual's generated set."""

    def __post_init__(self) -> None:
        """Validate every color is hex and required custom vars are present.

        Raises:
            ValueError: If any base color is not a hex string, if any pinned
                variable value is not a hex string, or if a required custom
                variable (`highlight` / `highlight-soft` / `boundary`) is
                missing.
        """
        for attr in (
            "primary",
            "secondary",
            "background",
            "surface",
            "foreground",
            "success",
            "warning",
            "error",
            "accent",
        ):
            val = getattr(self, attr)
            if not _HEX_RE.match(val):
                msg = f"ThemeSpec.{attr} must be a hex color, got {val!r}"
                raise ValueError(msg)
        for key, val in self.variables.items():
            if not _HEX_RE.match(val):
                msg = f"ThemeSpec.variables[{key!r}] must be a hex color, got {val!r}"
                raise ValueError(msg)
        missing = [v for v in _REQUIRED_CUSTOM_VARS if v not in self.variables]
        if missing:
            msg = f"ThemeSpec {self.name!r} missing required variables: {missing}"
            raise ValueError(msg)

    def to_theme(self) -> Theme:
        """Build the Textual `Theme` this spec describes.

        Returns:
            A `textual.theme.Theme` carrying the base colors and the pinned
            `variables`.
        """
        from textual.theme import Theme

        return Theme(
            name=self.name,
            primary=self.primary,
            secondary=self.secondary,
            warning=self.warning,
            error=self.error,
            success=self.success,
            accent=self.accent,
            foreground=self.foreground,
            background=self.background,
            surface=self.surface,
            dark=self.dark,
            variables=dict(self.variables),
        )


# ---------------------------------------------------------------------------
# Built-in themes
# ---------------------------------------------------------------------------

# The default. Every value here reproduces exactly what `app.tcss` used to
# hard-code (the MATTE SWAMP palette), so removing that override block leaves
# the default look byte-identical. The `variables` entries pin the derived
# and app-specific variables that Textual would otherwise compute (and get
# subtly wrong, e.g. `warning` rounds #b89968 -> #b79968).
BOG_SPEC = ThemeSpec(
    name="bog",
    label="Bog (peat)",
    dark=True,
    primary="#7aa888",
    secondary="#6a9b9b",
    background="#060a07",
    surface="#0d1410",
    foreground="#c8d4ca",
    success="#7aa888",
    warning="#b89968",
    error="#b86a78",
    # Preserves the two widgets whose borders reference `$accent`; this is the
    # value Textual's default dark theme resolved before the theme existed.
    accent="#ffa62b",
    variables={
        "primary-lighten-1": "#9cc4a7",
        "primary-lighten-2": "#c1d8c8",
        "primary-darken-1": "#557a63",
        "primary-darken-2": "#3a5a48",
        "surface-lighten-1": "#16201a",
        "surface-darken-1": "#040705",
        "highlight": "#1f3328",
        "highlight-soft": "#16271d",
        "boundary": "#243828",
        "text": "#c8d4ca",
        "text-muted": "#6f8478",
        "warning": "#b89968",
    },
)

BOG_LIGHT_SPEC = ThemeSpec(
    name="bog-light",
    label="Bog Light (parchment)",
    dark=False,
    primary="#4a7358",
    secondary="#4f7d7d",
    background="#eef1ec",
    surface="#e2e8df",
    foreground="#2b3630",
    success="#4a7358",
    warning="#8a6d34",
    error="#9c4757",
    accent="#b4791f",
    variables={
        "highlight": "#cfe0d4",
        "highlight-soft": "#dde9e0",
        "boundary": "#c2cfc4",
        "text": "#2b3630",
        "text-muted": "#5c6b62",
    },
)

ABYSS_SPEC = ThemeSpec(
    name="abyss",
    label="Abyss (cold marsh)",
    dark=True,
    primary="#6f9fb5",
    secondary="#8f7fb0",
    background="#05080c",
    surface="#0c1219",
    foreground="#c2cede",
    success="#6fae8f",
    warning="#b8a06a",
    error="#c07082",
    accent="#5fd0c0",
    variables={
        "highlight": "#14232e",
        "highlight-soft": "#0f1a23",
        "boundary": "#1e2f3a",
        "text": "#c2cede",
        "text-muted": "#66788a",
    },
)

EMBER_SPEC = ThemeSpec(
    name="ember",
    label="Ember (bog-fire)",
    dark=True,
    primary="#c08a5a",
    secondary="#9b8b6a",
    background="#0a0705",
    surface="#16100c",
    foreground="#ddd0c4",
    success="#8faa6a",
    warning="#cf9d55",
    error="#c56a5a",
    accent="#e0912b",
    variables={
        "highlight": "#2e2013",
        "highlight-soft": "#241a12",
        "boundary": "#3a2a1c",
        "text": "#ddd0c4",
        "text-muted": "#8a7a68",
    },
)

_BUILTIN_SPECS: tuple[ThemeSpec, ...] = (
    BOG_SPEC,
    BOG_LIGHT_SPEC,
    ABYSS_SPEC,
    EMBER_SPEC,
)


def builtin_theme_specs() -> tuple[ThemeSpec, ...]:
    """Return the built-in theme specs, `bog` first.

    Returns:
        The immutable tuple of built-in `ThemeSpec` instances.
    """
    return _BUILTIN_SPECS


# ---------------------------------------------------------------------------
# User themes
# ---------------------------------------------------------------------------


def _spec_from_section(name: str, section: Mapping[str, Any]) -> ThemeSpec | None:
    """Build a `ThemeSpec` from one `[themes.<name>]` config section.

    Unrecognized or malformed fields are logged and ignored; a section that
    cannot yield a valid spec (missing `label`, all-invalid colors) returns
    `None` rather than raising, so one bad user theme never blocks startup.

    Missing base colors fall back to the `bog` (dark) or `bog-light` (light)
    palette. Missing `highlight` / `highlight-soft` / `boundary` fall back to
    the same base so the required custom variables are always present.

    Args:
        name: The theme name (the `<name>` in `[themes.<name>]`).
        section: The parsed TOML table for this theme.

    Returns:
        A validated `ThemeSpec`, or `None` when the section is unusable.
    """
    label = section.get("label")
    if not isinstance(label, str) or not label.strip():
        logger.warning("User theme %r missing required 'label' (str); skipping", name)
        return None

    dark_raw = section.get("dark", True)
    if not isinstance(dark_raw, bool):
        logger.warning(
            "User theme %r: 'dark' must be true/false, got %r; defaulting to dark",
            name,
            dark_raw,
        )
        dark_raw = True

    base = BOG_SPEC if dark_raw else BOG_LIGHT_SPEC

    def _color(key: str, fallback: str) -> str:
        raw = section.get(key)
        if isinstance(raw, str) and _HEX_RE.match(raw):
            return raw
        if raw is not None:
            logger.warning(
                "User theme %r field %r is not a hex color (%r); using fallback",
                name,
                key,
                raw,
            )
        return fallback

    variables: dict[str, str] = {}
    for key in _PINNABLE_VARS:
        raw = section.get(key)
        if isinstance(raw, str) and _HEX_RE.match(raw):
            variables[key] = raw
        elif raw is not None:
            logger.warning(
                "User theme %r variable %r is not a hex color (%r); ignoring",
                name,
                key,
                raw,
            )
    # Guarantee the required custom vars exist by falling back to the base.
    for key in _REQUIRED_CUSTOM_VARS:
        variables.setdefault(key, base.variables[key])

    try:
        return ThemeSpec(
            name=name,
            label=label,
            dark=dark_raw,
            primary=_color("primary", base.primary),
            secondary=_color("secondary", base.secondary),
            background=_color("background", base.background),
            surface=_color("surface", base.surface),
            foreground=_color("foreground", base.foreground),
            success=_color("success", base.success),
            warning=_color("warning", base.warning),
            error=_color("error", base.error),
            accent=_color("accent", base.accent),
            variables=variables,
        )
    except ValueError:
        logger.warning("User theme %r is invalid; skipping", name, exc_info=True)
        return None


def load_user_theme_specs(
    config: Mapping[str, Any] | None = None,
) -> list[ThemeSpec]:
    """Load user-defined themes from `[themes.<name>]` config sections.

    A user section whose name matches a built-in theme is ignored (built-ins
    are authoritative); use a distinct name to add a theme.

    Args:
        config: Parsed `config.toml` mapping. When `None`, the user's
            `~/.bog-agents/config.toml` is read via
            `config_manifest.load_config_toml`.

    Returns:
        Validated user `ThemeSpec` instances (order follows the config file).
        Invalid sections are logged and skipped.
    """
    if config is None:
        try:
            from bog_agents_cli.config_manifest import load_config_toml

            config = load_config_toml()
        except Exception:
            logger.debug("Could not load config for user themes", exc_info=True)
            return []

    section = config.get("themes")
    if not isinstance(section, dict) or not section:
        return []

    builtin_names = {spec.name for spec in _BUILTIN_SPECS}
    specs: list[ThemeSpec] = []
    for name, table in section.items():
        if name in builtin_names:
            logger.warning(
                "User theme %r shadows a built-in theme name; ignoring", name
            )
            continue
        if not isinstance(table, dict):
            logger.warning("Ignoring non-table [themes.%s]", name)
            continue
        spec = _spec_from_section(name, table)
        if spec is not None:
            specs.append(spec)
    return specs


def all_theme_specs(config: Mapping[str, Any] | None = None) -> list[ThemeSpec]:
    """Return built-in specs followed by valid user specs.

    Args:
        config: Optional parsed config (see `load_user_theme_specs`).

    Returns:
        Built-in then user `ThemeSpec` instances.
    """
    return [*_BUILTIN_SPECS, *load_user_theme_specs(config)]


def theme_labels(config: Mapping[str, Any] | None = None) -> dict[str, str]:
    """Return an ordered `{name: label}` map of every available theme.

    Args:
        config: Optional parsed config (see `load_user_theme_specs`).

    Returns:
        Insertion-ordered mapping from theme name to its display label.
    """
    return {spec.name: spec.label for spec in all_theme_specs(config)}


def register_all_themes(
    app: App,
    *,
    config: Mapping[str, Any] | None = None,
) -> list[str]:
    """Register every built-in and user theme with the Textual app.

    Safe to call once during `on_mount`. Registration failures for a single
    theme are logged and skipped so one bad user theme cannot break startup.

    Args:
        app: The Textual application to register themes on.
        config: Optional parsed config (see `load_user_theme_specs`).

    Returns:
        The names of the themes successfully registered, in order.
    """
    registered: list[str] = []
    for spec in all_theme_specs(config):
        try:
            app.register_theme(spec.to_theme())
        except Exception:
            logger.warning("Could not register theme %r", spec.name, exc_info=True)
            continue
        registered.append(spec.name)
    return registered


def resolve_theme_name(
    requested: str,
    *,
    config: Mapping[str, Any] | None = None,
) -> str | None:
    """Return the exact theme name matching `requested`, or `None`.

    Matches case-insensitively against theme names so `/theme BOG` works.

    Args:
        requested: The user-supplied theme name.
        config: Optional parsed config (see `load_user_theme_specs`).

    Returns:
        The canonical theme name if found, otherwise `None`.
    """
    wanted = requested.strip().lower()
    for spec in all_theme_specs(config):
        if spec.name.lower() == wanted:
            return spec.name
    return None


@dataclass(frozen=True, slots=True)
class ThemeCommandResult:
    """Outcome of a non-interactive `/theme` invocation.

    Attributes:
        message: Text to show the user.
        apply: Theme name to switch to and persist, or `None` for list /
            error results where no switch should happen.
        is_error: Whether `message` describes a failure.
    """

    message: str
    apply: str | None = None
    is_error: bool = False


def handle_theme_command(
    arg: str,
    *,
    current: str | None = None,
    config: Mapping[str, Any] | None = None,
) -> ThemeCommandResult:
    """Pure controller for `/theme <arg>` (no TUI dependencies).

    `arg` is the text after `/theme`. `''` is handled by the caller (opens
    the picker) and should not reach here; if it does it is treated as
    `list`. `list` returns the catalog; anything else is treated as a theme
    name to switch to.

    Args:
        arg: The argument text after `/theme` (already stripped).
        current: The currently active theme name, marked in `list` output.
        config: Optional parsed config (see `load_user_theme_specs`).

    Returns:
        A `ThemeCommandResult` describing the message and whether to apply a
        theme.
    """
    normalized = arg.strip()
    if not normalized or normalized.lower() == "list":
        return ThemeCommandResult(message=_format_theme_list(current, config))

    resolved = resolve_theme_name(normalized, config=config)
    if resolved is None:
        names = ", ".join(theme_labels(config))
        return ThemeCommandResult(
            message=f"Unknown theme {normalized!r}. Available: {names}",
            is_error=True,
        )

    label = theme_labels(config).get(resolved, resolved)
    return ThemeCommandResult(
        message=f"Theme set to {label} ({resolved}).",
        apply=resolved,
    )


def _format_theme_list(
    current: str | None,
    config: Mapping[str, Any] | None,
) -> str:
    """Format the `/theme list` output.

    Args:
        current: The active theme name (marked with a bullet).
        config: Optional parsed config (see `load_user_theme_specs`).

    Returns:
        A multi-line string listing each theme's name and label.
    """
    lines = ["Available themes:"]
    for spec in all_theme_specs(config):
        marker = "*" if spec.name == current else " "
        variant = "dark" if spec.dark else "light"
        lines.append(f"  {marker} {spec.name} — {spec.label} ({variant})")
    lines.append("Use /theme <name> to switch, or /theme to open the picker.")
    return "\n".join(lines)


def theme_names(config: Mapping[str, Any] | None = None) -> Iterable[str]:
    """Yield every available theme name, built-ins first.

    Args:
        config: Optional parsed config (see `load_user_theme_specs`).

    Yields:
        Theme names in registration order.
    """
    for spec in all_theme_specs(config):
        yield spec.name
